import "./globals.css";
import Header from "./_components/header";
import { CartProvider } from './context/cartContext'
import Home from './customer/page';
import Footer from "./_components/footer";
export const metadata = {
  title: "E-commerce",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className="m-0">
        <div className="min-h-screen flex flex-col">
          <CartProvider>
            <Header />
            <main className="flex-grow">
              {children}
            </main>
            <Footer />
          </CartProvider>
        </div>
      </body>
    </html>
  );
}


