import "./globals.css";
import Header from "./_components/header";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="m-0 px-8">
        <Header/>
        {children}
      </body>
    </html>
  );
}
